spring:
  config:
    name: application
    import: optional:file:.env[.properties]

  application:
    name: dubidubap-server

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # H2 콘솔 설정 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Thymeleaf 설정
  thymeleaf:
    cache: false

server:
  port: 8080
  # 에러 응답 설정
  error:
    include-stacktrace: never
    include-message: on_param
    include-binding-errors: on_param

# 로깅 설정
logging:
  level:
    com.guineafigma: DEBUG

# Suno API 설정
suno:
  api:
    key: ${SUNO_API_KEY:your-suno-api-key}
    url: ${SUNO_API_URL:https://api.sunoapi.org}

# OpenAI API 설정 (가사 생성용)
openai:
  api:
    key: ${OPENAI_API_KEY:your-openai-api-key}
    url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
    model: ${OPENAI_MODEL:gpt-4o-mini}

# JWT 설정
jwt:
  secret-key: ${JWT_SECRET:defaultSecretKeyWhichIsSufficientlyLongForHMAC}
  expiration:
    access: ${JWT_EXPIRATION:14400000}
    refresh: ${JWT_REFRESH_EXPIRATION:604800000}
